<?php

use Illuminate\Database\Seeder;

class ArtistsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('artists')->delete();

        $artists = array(
            array('id' => '5','user_id' => NULL,'category_id' => '19','photo_id' => '40','status' => 'active','initials' => 'C.D.','pass' => '23235','title' => 'Celebration Duo','slug' => 'adam-sandler','body' => '<p>test etetewtewtewtew test etetewtewtewtewtest etetewtewtewtewtest etetewtewtewtewtest etetewtewtewtewtest etetewtewtewtewtest etetewtewtewtewtest etetewtewtewtewtest etetewtewtewtewtest etetewtewtewtewtest etetewtewtewtewtest etetewtewtewtewtest etetewtewtewtewtest etetewtewtewtewtest etetewtewtewtewtest etetewtewtewtewtest etetewtewtewtewtest etetewtewtewtewtest etetewtewtewtewtest etetewtewtewtew</p>','audio_id' => '9','audio2' => NULL,'audio3' => NULL,'video1' => 'https://www.youtube.com/watch?v=JxPj3GAYYZ0&list=RDEMAooSTA5wUMJn9sD-hZCR0g&start_radio=1','video2' => NULL,'video3' => NULL,'reference1' => 'Стоян Недев, Banevo, 0878771124','reference2' => NULL,'reference3' => NULL,'created_at' => '2019-06-05 08:31:17','updated_at' => '2019-06-27 11:20:25'),
            array('id' => '12','user_id' => NULL,'category_id' => '10','photo_id' => '30','status' => 'active','initials' => 'M.T.','pass' => '133','title' => 'Miro Trobadur','slug' => 'lili-ivanova','body' => '<p>Aenean id nisl eu felis tempus imperdiet. Sed dapibus hendrerit risus quis egestas. Praesent orci nisi, sagittis in augue vitae, porta sodales dui. Proin eu ante fermentum, porttitor arcu id, faucibus lectus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum egestas condimentum mauris, eget molestie risus gravida malesuada. Pellentesque rhoncus suscipit nisl vitae maximus. Nulla porttitor dictum dui, non aliquam nulla convallis id. Ut quis ex urna. Pellentesque eget rutrum ligula. Nulla ex massa, posuere ac nisl sit amet, efficitur semper dolor. Morbi et nunc faucibus, tincidunt ipsum ut, imperdiet quam. Ut accumsan, felis in mattis eleifend, velit ante convallis quam, et efficitur enim nibh eget nisl. Sed venenatis nisl vel justo ultricies, sed dictum tellus tristique.</p>
<p>Aenean id nisl eu felis tempus imperdiet. Sed dapibus hendrerit risus quis egestas. Praesent orci nisi, sagittis in augue vitae, porta sodales dui. Proin eu ante fermentum, porttitor arcu id, faucibus lectus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum egestas condimentum mauris, eget molestie risus gravida malesuada. Pellentesque rhoncus suscipit nisl vitae maximus. Nulla porttitor dictum dui, non aliquam nulla convallis id. Ut quis ex urna. Pellentesque eget rutrum ligula. Nulla ex massa, posuere ac nisl sit amet, efficitur semper dolor. Morbi et nunc faucibus, tincidunt ipsum ut, imperdiet quam. Ut accumsan, felis in mattis eleifend, velit ante convallis quam, et efficitur enim nibh eget nisl. Sed venenatis nisl vel justo ultricies, sed dictum tellus tristique.</p>','audio_id' => '7','audio2' => NULL,'audio3' => NULL,'video1' => 'https://www.youtube.com/watch?v=vUSzL2leaFM','video2' => NULL,'video3' => NULL,'reference1' => NULL,'reference2' => NULL,'reference3' => NULL,'created_at' => '2019-06-10 14:45:19','updated_at' => '2019-06-27 13:25:40'),
            array('id' => '13','user_id' => NULL,'category_id' => '13','photo_id' => '43','status' => 'active','initials' => 'L.J.B.','pass' => '1212','title' => 'Loid Jazz Band','slug' => 'loid-jazz-band','body' => '<p>Make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>','audio_id' => NULL,'audio2' => NULL,'audio3' => NULL,'video1' => 'https://www.youtube.com/watch?v=vUSzL2leaFM','video2' => NULL,'video3' => NULL,'reference1' => NULL,'reference2' => NULL,'reference3' => NULL,'created_at' => '2019-06-27 08:21:34','updated_at' => '2019-06-27 08:21:34'),
            array('id' => '14','user_id' => NULL,'category_id' => '8','photo_id' => '44','status' => 'active','initials' => 'P.A.','pass' => '43252','title' => 'Pavlina Ac','slug' => 'pavlina-ac','body' => '<p>Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>','audio_id' => '10','audio2' => NULL,'audio3' => NULL,'video1' => 'https://www.youtube.com/watch?v=vUSzL2leaFM','video2' => NULL,'video3' => NULL,'reference1' => NULL,'reference2' => NULL,'reference3' => NULL,'created_at' => '2019-06-27 08:34:56','updated_at' => '2019-06-27 13:29:41'),
            array('id' => '15','user_id' => NULL,'category_id' => '8','photo_id' => '45','status' => 'active','initials' => 'F.P.B.','pass' => '543','title' => 'Filip','slug' => 'jose-carrera','body' => '<p>All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc</p>','audio_id' => '11','audio2' => NULL,'audio3' => NULL,'video1' => 'https://www.youtube.com/watch?v=JxPj3GAYYZ0&list=RDEMAooSTA5wUMJn9sD-hZCR0g&start_radio=1','video2' => NULL,'video3' => NULL,'reference1' => NULL,'reference2' => NULL,'reference3' => NULL,'created_at' => '2019-06-27 08:35:52','updated_at' => '2019-06-27 08:42:18'),
            array('id' => '16','user_id' => NULL,'category_id' => '8','photo_id' => '46','status' => 'active','initials' => 'I.G.','pass' => '0922','title' => 'Ivo Gee','slug' => 'ivo-gee','body' => '<p>The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.</p>','audio_id' => '12','audio2' => NULL,'audio3' => NULL,'video1' => 'https://www.youtube.com/watch?v=uS90B4sZf7U&list=RDHzTlB-TjAzM&index=4','video2' => NULL,'video3' => NULL,'reference1' => NULL,'reference2' => NULL,'reference3' => NULL,'created_at' => '2019-06-27 11:34:22','updated_at' => '2019-06-27 11:34:22')
        );



        DB::table('artists')->insert($artists);
    }
}
