<?php

use Illuminate\Database\Seeder;

class ArtistsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('artists')->delete();

        $artists = array(
            array('id' => '8','user_id' => NULL,'category_id' => '8','photo_id' => '15','status' => 'active','initials' => NULL,'pass' => NULL,'title' => 'Произволен Артистов','slug' => 'proizvolen-artistov','body' => '<p>Nam suscipit turpis eu fermentum placerat. Donec justo nunc, facilisis eu ullamcorper commodo, molestie et mi. Nulla mollis malesuada libero non ultrices. Aliquam venenatis egestas diam vitae posuere. Cras maximus ultricies magna, a tempus eros finibus in. Vestibulum a diam massa. Mauris molestie velit quam, ut ultricies quam euismod sit amet. Sed facilisis sagittis massa ac congue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus mauris eros, porttitor quis nulla venenatis, tempor malesuada sapien. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In volutpat consequat turpis molestie lobortis. Donec neque justo, gravida et libero nec, vulputate condimentum ligula. Vestibulum turpis lacus, cursus quis erat sit amet, ornare sagittis neque.</p>
<p><img src="/images/1/images/adult-background-casual-941693.jpg" alt="" width="222" height="333" /></p>
<p>&nbsp;</p>
<p>&nbsp;</p>','audio_id' => '1','audio2' => NULL,'audio3' => NULL,'video1' => 'https://www.youtube.com/watch?v=2BagnXBvY4M','video2' => NULL,'video3' => NULL,'reference1' => '0878771124','reference2' => 'kirili ivanov','reference3' => NULL,'created_at' => '2019-06-05 13:52:26','updated_at' => '2019-06-10 09:12:22'),
            array('id' => '3','user_id' => NULL,'category_id' => '8','photo_id' => '3','status' => 'active','initials' => NULL,'pass' => NULL,'title' => 'Jose Maria Batistuta','slug' => 'jose-maria-batistuta','body' => '<p>test wrewewewe</p>','audio_id' => NULL,'audio2' => NULL,'audio3' => NULL,'video1' => 'https://www.youtube.com/watch?v=2BagnXBvY4M','video2' => NULL,'video3' => NULL,'reference1' => NULL,'reference2' => NULL,'reference3' => NULL,'created_at' => '2019-06-04 14:58:46','updated_at' => '2019-06-10 08:02:53'),
            array('id' => '4','user_id' => NULL,'category_id' => '5','photo_id' => '2','status' => 'active','initials' => 'E.C.','pass' => '245','title' => 'Eric Clapton','slug' => 'eric-clapton','body' => '<p>Morbi nec lorem orci. Vestibulum fermentum molestie ex, vitae suscipit metus luctus a. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent vel eleifend massa. Aliquam fringilla sollicitudin urna, in commodo est gravida sed. Aliquam ultricies nunc sed libero euismod, id ullamcorper leo faucibus. Praesent non sodales ante. Morbi condimentum tellus ullamcorper sem consectetur, a semper enim aliquam. Proin accumsan nulla in arcu fermentum lacinia. Sed vestibulum metus nibh, nec feugiat erat laoreet eu. Suspendisse potenti. Aliquam non purus nisi. Nulla et sem nibh. Nullam maximus egestas diam, at volutpat nisl vestibulum non.</p>','audio_id' => '4','audio2' => NULL,'audio3' => NULL,'video1' => 'https://www.youtube.com/watch?v=2BagnXBvY4M','video2' => NULL,'video3' => NULL,'reference1' => '0878771124','reference2' => NULL,'reference3' => NULL,'created_at' => '2019-06-05 08:27:12','updated_at' => '2019-06-10 16:54:52'),
            array('id' => '5','user_id' => NULL,'category_id' => '7','photo_id' => '6','status' => 'active','initials' => 'A.S.','pass' => '2323','title' => 'Adam Sandler','slug' => 'adam-sandler','body' => '<p>test etetewtewtewtew</p>','audio_id' => '9','audio2' => NULL,'audio3' => NULL,'video1' => NULL,'video2' => NULL,'video3' => NULL,'reference1' => NULL,'reference2' => NULL,'reference3' => NULL,'created_at' => '2019-06-05 08:31:17','updated_at' => '2019-06-15 18:08:25'),
            array('id' => '6','user_id' => NULL,'category_id' => '6','photo_id' => '5','status' => 'active','initials' => 'B.K.','pass' => '09','title' => 'Belinda Karlile','slug' => 'balinda-karlile','body' => '<p>Morbi nisl dolor, aliquam sit amet sem a, volutpat sollicitudin velit. Donec elementum nisl ut sem malesuada, in condimentum nibh imperdiet. Etiam laoreet placerat lectus, ut elementum eros aliquam eu. Aliquam porta elementum pretium. Maecenas malesuada quam in nunc vehicula, in hendrerit risus viverra. Duis pulvinar mollis neque eu sodales. Sed fermentum ex ut tellus scelerisque eleifend. Donec venenatis commodo turpis, at ornare mauris. Duis sit amet finibus augue. Aliquam quis dignissim turpis. Nulla facilisi. Vivamus pulvinar elit in lorem pellentesque hendrerit. Maecenas volutpat molestie libero vitae accumsan.</p>','audio_id' => '8','audio2' => NULL,'audio3' => NULL,'video1' => 'https://www.youtube.com/watch?v=2BagnXBvY4M','video2' => NULL,'video3' => NULL,'reference1' => '0878771124','reference2' => 'kirili ivanov','reference3' => NULL,'created_at' => '2019-06-05 09:13:53','updated_at' => '2019-06-13 14:27:52'),
            array('id' => '9','user_id' => NULL,'category_id' => '5','photo_id' => '27','status' => 'active','initials' => 'J.D.','pass' => '6565','title' => 'Jonattan Davis','slug' => 'jonattan-davis','body' => '<p>Morbi molestie arcu sagittis imperdiet volutpat. Curabitur molestie lacus in odio sagittis ornare. Aliquam vehicula aliquet aliquam. Pellentesque vitae suscipit risus, sed vestibulum dui. Nullam quam arcu, sagittis vel ultricies in, porta sit amet mauris. Nunc et purus id tellus malesuada luctus a vel justo. Etiam egestas efficitur sagittis.</p>
<p>Morbi molestie arcu sagittis imperdiet volutpat. Curabitur molestie lacus in odio sagittis ornare. Aliquam vehicula aliquet aliquam. Pellentesque vitae suscipit risus, sed vestibulum dui. Nullam quam arcu, sagittis vel ultricies in, porta sit amet mauris. Nunc et purus id tellus malesuada luctus a vel justo. Etiam egestas efficitur sagittis.</p>
<p>Morbi molestie arcu sagittis imperdiet volutpat. Curabitur molestie lacus in odio sagittis ornare. Aliquam vehicula aliquet aliquam. Pellentesque vitae suscipit risus, sed vestibulum dui. Nullam quam arcu, sagittis vel ultricies in, porta sit amet mauris. Nunc et purus id tellus malesuada luctus a vel justo. Etiam egestas efficitur sagittis.</p>
<p>Morbi molestie arcu sagittis imperdiet volutpat. Curabitur molestie lacus in odio sagittis ornare. Aliquam vehicula aliquet aliquam. Pellentesque vitae suscipit risus, sed vestibulum dui. Nullam quam arcu, sagittis vel ultricies in, porta sit amet mauris. Nunc et purus id tellus malesuada luctus a vel justo. Etiam egestas efficitur sagittis.</p>
<p>Morbi molestie arcu sagittis imperdiet volutpat. Curabitur molestie lacus in odio sagittis ornare. Aliquam vehicula aliquet aliquam. Pellentesque vitae suscipit risus, sed vestibulum dui. Nullam quam arcu, sagittis vel ultricies in, porta sit amet mauris. Nunc et purus id tellus malesuada luctus a vel justo. Etiam egestas efficitur sagittis.</p>','audio_id' => '2','audio2' => NULL,'audio3' => NULL,'video1' => 'https://www.youtube.com/watch?v=vUSzL2leaFM','video2' => NULL,'video3' => NULL,'reference1' => 'Стоян Недев 0878771124','reference2' => NULL,'reference3' => NULL,'created_at' => '2019-06-10 09:14:41','updated_at' => '2019-06-17 10:28:09'),
            array('id' => '10','user_id' => NULL,'category_id' => '5','photo_id' => '28','status' => 'active','initials' => 'M.J.B.','pass' => '343','title' => 'Manhattan Jazz Band','slug' => 'manhattan-jazz-band','body' => '<p>Sed eleifend enim at nisi euismod volutpat. Phasellus pretium dignissim orci id gravida. Praesent finibus posuere nunc at aliquam. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nam aliquet lacus sed metus condimentum gravida. Sed pharetra orci non rhoncus condimentum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum eu libero in leo hendrerit porta. Vestibulum hendrerit mattis nulla, id convallis felis mattis sit amet.</p>
<p>Sed eleifend enim at nisi euismod volutpat. Phasellus pretium dignissim orci id gravida. Praesent finibus posuere nunc at aliquam. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nam aliquet lacus sed metus condimentum gravida. Sed pharetra orci non rhoncus condimentum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum eu libero in leo hendrerit porta. Vestibulum hendrerit mattis nulla, id convallis felis mattis sit amet.</p>
<p>Sed eleifend enim at nisi euismod volutpat. Phasellus pretium dignissim orci id gravida. Praesent finibus posuere nunc at aliquam. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nam aliquet lacus sed metus condimentum gravida. Sed pharetra orci non rhoncus condimentum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum eu libero in leo hendrerit porta. Vestibulum hendrerit mattis nulla, id convallis felis mattis sit amet.</p>','audio_id' => '5','audio2' => NULL,'audio3' => NULL,'video1' => 'https://www.youtube.com/watch?v=vUSzL2leaFM','video2' => NULL,'video3' => NULL,'reference1' => 'Стоян Недев 0878771124','reference2' => NULL,'reference3' => NULL,'created_at' => '2019-06-10 09:18:02','updated_at' => '2019-06-14 14:54:42'),
            array('id' => '11','user_id' => NULL,'category_id' => '6','photo_id' => '29','status' => 'active','initials' => 'Кеца','pass' => '55','title' => 'Васил Найденов','slug' => 'vasil-naydenov','body' => '<p>Sed faucibus egestas tincidunt. In vestibulum luctus mollis. Etiam a posuere felis. Sed neque velit, aliquam non augue sodales, pretium fringilla libero. Mauris nec quam blandit, vestibulum justo a, blandit metus. In hac habitasse platea dictumst. Nullam egestas nisl vel risus sagittis suscipit. Morbi non viverra nulla, sed finibus est. Ut molestie sapien lobortis libero vehicula rhoncus. Cras sem nisl, porta quis lectus tincidunt, viverra pulvinar elit. Donec dictum quam ut condimentum semper.</p>
<p>Sed faucibus egestas tincidunt. In vestibulum luctus mollis. Etiam a posuere felis. Sed neque velit, aliquam non augue sodales, pretium fringilla libero. Mauris nec quam blandit, vestibulum justo a, blandit metus. In hac habitasse platea dictumst. Nullam egestas nisl vel risus sagittis suscipit. Morbi non viverra nulla, sed finibus est. Ut molestie sapien lobortis libero vehicula rhoncus. Cras sem nisl, porta quis lectus tincidunt, viverra pulvinar elit. Donec dictum quam ut condimentum semper.</p>
<p>Sed faucibus egestas tincidunt. In vestibulum luctus mollis. Etiam a posuere felis. Sed neque velit, aliquam non augue sodales, pretium fringilla libero. Mauris nec quam blandit, vestibulum justo a, blandit metus. In hac habitasse platea dictumst. Nullam egestas nisl vel risus sagittis suscipit. Morbi non viverra nulla, sed finibus est. Ut molestie sapien lobortis libero vehicula rhoncus. Cras sem nisl, porta quis lectus tincidunt, viverra pulvinar elit. Donec dictum quam ut condimentum semper.</p>','audio_id' => '6','audio2' => NULL,'audio3' => NULL,'video1' => 'https://www.youtube.com/watch?v=2BagnXBvY4M','video2' => NULL,'video3' => NULL,'reference1' => 'Стоян Недев 0878771124','reference2' => NULL,'reference3' => NULL,'created_at' => '2019-06-10 14:39:17','updated_at' => '2019-06-10 14:43:17'),
            array('id' => '12','user_id' => NULL,'category_id' => '5','photo_id' => '30','status' => 'active','initials' => 'L.I.','pass' => '133','title' => 'Lili Ivanova','slug' => 'lili-ivanova','body' => '<p>Aenean id nisl eu felis tempus imperdiet. Sed dapibus hendrerit risus quis egestas. Praesent orci nisi, sagittis in augue vitae, porta sodales dui. Proin eu ante fermentum, porttitor arcu id, faucibus lectus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum egestas condimentum mauris, eget molestie risus gravida malesuada. Pellentesque rhoncus suscipit nisl vitae maximus. Nulla porttitor dictum dui, non aliquam nulla convallis id. Ut quis ex urna. Pellentesque eget rutrum ligula. Nulla ex massa, posuere ac nisl sit amet, efficitur semper dolor. Morbi et nunc faucibus, tincidunt ipsum ut, imperdiet quam. Ut accumsan, felis in mattis eleifend, velit ante convallis quam, et efficitur enim nibh eget nisl. Sed venenatis nisl vel justo ultricies, sed dictum tellus tristique.</p>
<p>Aenean id nisl eu felis tempus imperdiet. Sed dapibus hendrerit risus quis egestas. Praesent orci nisi, sagittis in augue vitae, porta sodales dui. Proin eu ante fermentum, porttitor arcu id, faucibus lectus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum egestas condimentum mauris, eget molestie risus gravida malesuada. Pellentesque rhoncus suscipit nisl vitae maximus. Nulla porttitor dictum dui, non aliquam nulla convallis id. Ut quis ex urna. Pellentesque eget rutrum ligula. Nulla ex massa, posuere ac nisl sit amet, efficitur semper dolor. Morbi et nunc faucibus, tincidunt ipsum ut, imperdiet quam. Ut accumsan, felis in mattis eleifend, velit ante convallis quam, et efficitur enim nibh eget nisl. Sed venenatis nisl vel justo ultricies, sed dictum tellus tristique.</p>','audio_id' => '7','audio2' => NULL,'audio3' => NULL,'video1' => 'https://www.youtube.com/watch?v=vUSzL2leaFM','video2' => NULL,'video3' => NULL,'reference1' => 'Стоян Недев, Banevo, 0878771124','reference2' => NULL,'reference3' => NULL,'created_at' => '2019-06-10 14:45:19','updated_at' => '2019-06-14 14:26:30')
        );



        DB::table('artists')->insert($artists);
    }
}
